### ISSUE TITLE
Where is ROS_ROOT?

### ISSUE THREAD

**Issue by realtime-neil** [ros/rosconsole#32]
Do I detect some discrepancy in how `ROS_ROOT` is documented?

There's this:

> // Next try to load the default config file from ROS_ROOT/config/rosconsole.config

-- https://github.com/ros/rosconsole/blob/6135fd34af6b3b48b2c779ec6626db7c2147048b/src/rosconsole/impl/rosconsole_log4cxx.cpp#L139

...which seems to agree with these:

```
$ cat /opt/ros/kinetic/share/ros/config/rosconsole.config
#
#   rosconsole will find this file by default at $ROS_ROOT/config/rosconsole.config
#
#   You can define your own by e.g. copying this file and setting
#   ROSCONSOLE_CONFIG_FILE (in your environment) to point to the new file
#
log4j.logger.ros=INFO
log4j.logger.ros.roscpp.superdebug=WARN
$ ( . /opt/ros/kinetic/setup.sh; echo "\${ROS_ROOT}=${ROS_ROOT}";)
${ROS_ROOT}=/opt/ros/kinetic/share/ros
```

But then, there's this:
> ROS_ROOT sets the location where the ROS core packages are installed.
> `export ROS_ROOT=/home/user/ros/ros`
> `export PATH=$ROS_ROOT/bin:$PATH`

-- https://wiki.ros.org/ROS/EnvironmentVariables#ROS_ROOT

...which doesn't seem to exist in my installation:

```
$ ( . /opt/ros/kinetic/setup.sh; test -d "${ROS_ROOT}/bin"; echo $?; )
1
```

Is the documentation incorrect?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
